### PR TITLE
fix: build error, formatting, lints

### PR DESCRIPTION
**Pull request by adamperkowski**

### CODE REVIEW

**Comment by cartercanedy** [comment]
I didn't realize the latest commit wasn't compiling, thanks for catching that. I have a bunch of changes uncommitted on my machine still, which does build, though, so I'll cherry pick from your PR and push those directly into master

**Comment by cartercanedy** [comment]
Thank you, again!

**Comment by adamperkowski** [comment]
> I didn't realize the latest commit wasn't compiling, thanks for catching that. I have a bunch of changes uncommitted on my machine still, which does build, though, so I'll cherry pick from your PR and push those directly into master

(remember to co-author) (jk, not that important. but still)

**Comment by adamperkowski** [comment]
You know you can close issues and PRs by putting the [closing keywords](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) in a commit's description?

Example:
https://github.com/adamperkowski/nvrs/commit/8322adaac003dd9210bd291399b275eb5daaf673
https://github.com/adamperkowski/nvrs/issues/2

**Comment by cartercanedy** [comment]
had no idea, thanks for the tip!

**Pull request closed without merging**
